# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41b4e3bb3fdbc7e1caffb339ad60a238888638faa535975ceeda56e07f1a9a594148ad07eaf78c108907451ccdc5f9d14742475cbfc46fe4e3a07a71158cf993
  associate_tag: <%= ENV["ASSOCIATE_TAG"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  rakuten_application_id: <%= ENV["RAKUTEN_APP_ID"] %>
  rakuten_affiliate_id: <%= ENV["RAKUTEN_AFFILIATE_ID"] %>

test:
  secret_key_base: 446a126fd69393f22a625952c67f9fa31b491a8456f83cb8d0094a42c146ead26d0d9af7d75e2df46041095653e9a3cf35546fa87bc5ca86afaf44f2280a50a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  associate_tag: <%= ENV["ASSOCIATE_TAG"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  rakuten_application_id: <%= ENV["RAKUTEN_APP_ID"] %>
  rakuten_affiliate_id: <%= ENV["RAKUTEN_AFFILIATE_ID"] %>
